[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 300"
